Make release workflow handle initial release?
There was no v1 branch when the workflow ran

    Run git push origin HEAD:v1
      git push origin HEAD:v1
      shell: /usr/bin/bash -e {0}
    error: The destination you provided is not a full refname (i.e.,
    starting with "refs/"). We tried to guess what you meant by:
    - Looking for a ref that matches 'v1' on the remote side.
    - Checking if the <src> being pushed ('HEAD')
      is a ref in "refs/{heads,tags}/". If so we add a corresponding
      refs/{heads,tags}/ prefix on the remote side.
    Neither worked, so we gave up. You must fully qualify the ref.
    hint: The <src> part of the refspec is a commit object.
    hint: Did you mean to create a new branch by pushing to
    hint: 'HEAD:refs/heads/v1'?
    error: failed to push some refs to 'https://github.com/dentarg/gem-compare'
    Error: Process completed with exit code 1.

Will this work well for future releases? Time will tell.