Use Ubuntu 22.04
    Run sudo gem install gem-compare --version $GEM_COMPARE_VERSION
    ERROR:  Error installing gem-compare:
            There are no versions of gem-compare (= 1.1.0) compatible with your Ruby & RubyGems
            gem-compare requires Ruby version >= 3.0.0. The current ruby version is 2.7.0.0.

Ubuntu has Ruby 3.0

https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2204-Readme.md#language-and-runtime